export const CURRENCIES = [
  { code: 'AED', flag: '🇦🇪', country: 'ae', name: 'UAE Dirham' },
  { code: 'AFN', flag: '🇦🇫', country: 'af', name: 'Afghan Afghani' },
  { code: 'ALL', flag: '🇦🇱', country: 'al', name: 'Albanian Lek' },
  { code: 'AMD', flag: '🇦🇲', country: 'am', name: 'Armenian Dram' },
  { code: 'ANG', flag: '🇨🇼', country: 'cw', name: 'NL Antillean Guilder' },
  { code: 'AOA', flag: '🇦🇴', country: 'ao', name: 'Angolan Kwanza' },
  { code: 'ARS', flag: '🇦🇷', country: 'ar', name: 'Argentine Peso' },
  { code: 'AUD', flag: '🇦🇺', country: 'au', name: 'Australian Dollar' },
  { code: 'AWG', flag: '🇦🇼', country: 'aw', name: 'Aruban Florin' },
  { code: 'AZN', flag: '🇦🇿', country: 'az', name: 'Azerbaijani Manat' },
  { code: 'BAM', flag: '🇧🇦', country: 'ba', name: 'Bosnia-Herz Convertible Mark' },
  { code: 'BBD', flag: '🇧🇧', country: 'bb', name: 'Barbadian Dollar' },
  { code: 'BDT', flag: '🇧🇩', country: 'bd', name: 'Bangladeshi Taka' },
  { code: 'BGN', flag: '🇧🇬', country: 'bg', name: 'Bulgarian Lev' },
  { code: 'BHD', flag: '🇧🇭', country: 'bh', name: 'Bahraini Dinar' },
  { code: 'BIF', flag: '🇧🇮', country: 'bi', name: 'Burundian Franc' },
  { code: 'BMD', flag: '🇧🇲', country: 'bm', name: 'Bermudan Dollar' },
  { code: 'BND', flag: '🇧🇳', country: 'bn', name: 'Brunei Dollar' },
  { code: 'BOB', flag: '🇧🇴', country: 'bo', name: 'Bolivian Boliviano' },
  { code: 'BRL', flag: '🇧🇷', country: 'br', name: 'Brazilian Real' },
  { code: 'BSD', flag: '🇧🇸', country: 'bs', name: 'Bahamian Dollar' },
  { code: 'BTN', flag: '🇧🇹', country: 'bt', name: 'Bhutanese Ngultrum' },
  { code: 'BWP', flag: '🇧🇼', country: 'bw', name: 'Botswanan Pula' },
  { code: 'BYN', flag: '🇧🇾', country: 'by', name: 'Belarusian Ruble' },
  { code: 'BZD', flag: '🇧🇿', country: 'bz', name: 'Belize Dollar' },
  { code: 'CAD', flag: '🇨🇦', country: 'ca', name: 'Canadian Dollar' },
  { code: 'CDF', flag: '🇨🇩', country: 'cd', name: 'Congolese Franc' },
  { code: 'CHF', flag: '🇨🇭', country: 'ch', name: 'Swiss Franc' },
  { code: 'CLP', flag: '🇨🇱', country: 'cl', name: 'Chilean Peso' },
  { code: 'CNY', flag: '🇨🇳', country: 'cn', name: 'Chinese Yuan' },
  { code: 'COP', flag: '🇨🇴', country: 'co', name: 'Colombian Peso' },
  { code: 'CRC', flag: '🇨🇷', country: 'cr', name: 'Costa Rican Colón' },
  { code: 'CUP', flag: '🇨🇺', country: 'cu', name: 'Cuban Peso' },
  { code: 'CVE', flag: '🇨🇻', country: 'cv', name: 'Cape Verdean Escudo' },
  { code: 'CZK', flag: '🇨🇿', country: 'cz', name: 'Czech Koruna' },
  { code: 'DJF', flag: '🇩🇯', country: 'dj', name: 'Djiboutian Franc' },
  { code: 'DKK', flag: '🇩🇰', country: 'dk', name: 'Danish Krone' },
  { code: 'DOP', flag: '🇩🇴', country: 'do', name: 'Dominican Peso' },
  { code: 'DZD', flag: '🇩🇿', country: 'dz', name: 'Algerian Dinar' },
  { code: 'EGP', flag: '🇪🇬', country: 'eg', name: 'Egyptian Pound' },
  { code: 'ERN', flag: '🇪🇷', country: 'er', name: 'Eritrean Nakfa' },
  { code: 'ETB', flag: '🇪🇹', country: 'et', name: 'Ethiopian Birr' },
  { code: 'EUR', flag: '🇪🇺', country: 'eu', name: 'Euro' },
  { code: 'FJD', flag: '🇫🇯', country: 'fj', name: 'Fijian Dollar' },
  { code: 'FKP', flag: '🇫🇰', country: 'fk', name: 'Falkland Islands Pound' },
  { code: 'GBP', flag: '🇬🇧', country: 'gb', name: 'British Pound' },
  { code: 'GEL', flag: '🇬🇪', country: 'ge', name: 'Georgian Lari' },
  { code: 'GHS', flag: '🇬🇭', country: 'gh', name: 'Ghanaian Cedi' },
  { code: 'GIP', flag: '🇬🇮', country: 'gi', name: 'Gibraltar Pound' },
  { code: 'GMD', flag: '🇬🇲', country: 'gm', name: 'Gambian Dalasi' },
  { code: 'GNF', flag: '🇬🇳', country: 'gn', name: 'Guinean Franc' },
  { code: 'GTQ', flag: '🇬🇹', country: 'gt', name: 'Guatemalan Quetzal' },
  { code: 'GYD', flag: '🇬🇾', country: 'gy', name: 'Guyanaese Dollar' },
  { code: 'HKD', flag: '🇭🇰', country: 'hk', name: 'Hong Kong Dollar' },
  { code: 'HNL', flag: '🇭🇳', country: 'hn', name: 'Honduran Lempira' },
  { code: 'HRK', flag: '🇭🇷', country: 'hr', name: 'Croatian Kuna' },
  { code: 'HTG', flag: '🇭🇹', country: 'ht', name: 'Haitian Gourde' },
  { code: 'HUF', flag: '🇭🇺', country: 'hu', name: 'Hungarian Forint' },
  { code: 'IDR', flag: '🇮🇩', country: 'id', name: 'Indonesian Rupiah' },
  { code: 'ILS', flag: '🇮🇱', country: 'il', name: 'Israeli New Shekel' },
  { code: 'INR', flag: '🇮🇳', country: 'in', name: 'Indian Rupee' },
  { code: 'IQD', flag: '🇮🇶', country: 'iq', name: 'Iraqi Dinar' },
  { code: 'IRR', flag: '🇮🇷', country: 'ir', name: 'Iranian Rial' },
  { code: 'ISK', flag: '🇮🇸', country: 'is', name: 'Icelandic Króna' },
  { code: 'JMD', flag: '🇯🇲', country: 'jm', name: 'Jamaican Dollar' },
  { code: 'JOD', flag: '🇯🇴', country: 'jo', name: 'Jordanian Dinar' },
  { code: 'JPY', flag: '🇯🇵', country: 'jp', name: 'Japanese Yen' },
  { code: 'KES', flag: '🇰🇪', country: 'ke', name: 'Kenyan Shilling' },
  { code: 'KGS', flag: '🇰🇬', country: 'kg', name: 'Kyrgystani Som' },
  { code: 'KHR', flag: '🇰🇭', country: 'kh', name: 'Cambodian Riel' },
  { code: 'KMF', flag: '🇰🇲', country: 'km', name: 'Comorian Franc' },
  { code: 'KPW', flag: '🇰🇵', country: 'kp', name: 'North Korean Won' },
  { code: 'KRW', flag: '🇰🇷', country: 'kr', name: 'South Korean Won' },
  { code: 'KWD', flag: '🇰🇼', country: 'kw', name: 'Kuwaiti Dinar' },
  { code: 'KYD', flag: '🇰🇾', country: 'ky', name: 'Cayman Islands Dollar' },
  { code: 'KZT', flag: '🇰🇿', country: 'kz', name: 'Kazakhstani Tenge' },
  { code: 'LAK', flag: '🇱🇦', country: 'la', name: 'Laotian Kip' },
  { code: 'LBP', flag: '🇱🇧', country: 'lb', name: 'Lebanese Pound' },
  { code: 'LKR', flag: '🇱🇰', country: 'lk', name: 'Sri Lankan Rupee' },
  { code: 'LRD', flag: '🇱🇷', country: 'lr', name: 'Liberian Dollar' },
  { code: 'LSL', flag: '🇱🇸', country: 'ls', name: 'Lesotho Loti' },
  { code: 'LYD', flag: '🇱🇾', country: 'ly', name: 'Libyan Dinar' },
  { code: 'MAD', flag: '🇲🇦', country: 'ma', name: 'Moroccan Dirham' },
  { code: 'MDL', flag: '🇲🇩', country: 'md', name: 'Moldovan Leu' },
  { code: 'MGA', flag: '🇲🇬', country: 'mg', name: 'Malagasy Ariary' },
  { code: 'MKD', flag: '🇲🇰', country: 'mk', name: 'Macedonian Denar' },
  { code: 'MMK', flag: '🇲🇲', country: 'mm', name: 'Myanmar Kyat' },
  { code: 'MNT', flag: '🇲🇳', country: 'mn', name: 'Mongolian Tugrik' },
  { code: 'MOP', flag: '🇲🇴', country: 'mo', name: 'Macanese Pataca' },
  { code: 'MRU', flag: '🇲🇷', country: 'mr', name: 'Mauritanian Ouguiya' },
  { code: 'MUR', flag: '🇲🇺', country: 'mu', name: 'Mauritian Rupee' },
  { code: 'MVR', flag: '🇲🇻', country: 'mv', name: 'Maldivian Rufiyaa' },
  { code: 'MWK', flag: '🇲🇼', country: 'mw', name: 'Malawian Kwacha' },
  { code: 'MXN', flag: '🇲🇽', country: 'mx', name: 'Mexican Peso' },
  { code: 'MYR', flag: '🇲🇾', country: 'my', name: 'Malaysian Ringgit' },
  { code: 'MZN', flag: '🇲🇿', country: 'mz', name: 'Mozambican Metical' },
  { code: 'NAD', flag: '🇳🇦', country: 'na', name: 'Namibian Dollar' },
  { code: 'NGN', flag: '🇳🇬', country: 'ng', name: 'Nigerian Naira' },
  { code: 'NIO', flag: '🇳🇮', country: 'ni', name: 'Nicaraguan Córdoba' },
  { code: 'NOK', flag: '🇳🇴', country: 'no', name: 'Norwegian Krone' },
  { code: 'NPR', flag: '🇳🇵', country: 'np', name: 'Nepalese Rupee' },
  { code: 'NZD', flag: '🇳🇿', country: 'nz', name: 'New Zealand Dollar' },
  { code: 'OMR', flag: '🇴🇲', country: 'om', name: 'Omani Rial' },
  { code: 'PAB', flag: '🇵🇦', country: 'pa', name: 'Panamanian Balboa' },
  { code: 'PEN', flag: '🇵🇪', country: 'pe', name: 'Peruvian Nuevo Sol' },
  { code: 'PGK', flag: '🇵🇬', country: 'pg', name: 'Papua New Guinean Kina' },
  { code: 'PHP', flag: '🇵🇭', country: 'ph', name: 'Philippine Peso' },
  { code: 'PKR', flag: '🇵🇰', country: 'pk', name: 'Pakistani Rupee' },
  { code: 'PLN', flag: '🇵🇱', country: 'pl', name: 'Polish Zloty' },
  { code: 'PYG', flag: '🇵🇾', country: 'py', name: 'Paraguayan Guarani' },
  { code: 'QAR', flag: '🇶🇦', country: 'qa', name: 'Qatari Rial' },
  { code: 'RON', flag: '🇷🇴', country: 'ro', name: 'Romanian Leu' },
  { code: 'RSD', flag: '🇷🇸', country: 'rs', name: 'Serbian Dinar' },
  { code: 'RUB', flag: '🇷🇺', country: 'ru', name: 'Russian Ruble' },
  { code: 'RWF', flag: '🇷🇼', country: 'rw', name: 'Rwandan Franc' },
  { code: 'SAR', flag: '🇸🇦', country: 'sa', name: 'Saudi Riyal' },
  { code: 'SBD', flag: '🇸🇧', country: 'sb', name: 'Solomon Islands Dollar' },
  { code: 'SCR', flag: '🇸🇨', country: 'sc', name: 'Seychellois Rupee' },
  { code: 'SDG', flag: '🇸🇩', country: 'sd', name: 'Sudanese Pound' },
  { code: 'SEK', flag: '🇸🇪', country: 'se', name: 'Swedish Krona' },
  { code: 'SGD', flag: '🇸🇬', country: 'sg', name: 'Singapore Dollar' },
  { code: 'SHP', flag: '🇸🇭', country: 'sh', name: 'Saint Helena Pound' },
  { code: 'SLL', flag: '🇸🇱', country: 'sl', name: 'Sierra Leonean Leone' },
  { code: 'SOS', flag: '🇸🇴', country: 'so', name: 'Somali Shilling' },
  { code: 'SRD', flag: '🇸🇷', country: 'sr', name: 'Surinamese Dollar' },
  { code: 'SSP', flag: '🇸🇸', country: 'ss', name: 'South Sudanese Pound' },
  { code: 'STN', flag: '🇸🇹', country: 'st', name: 'São Tomé and Príncipe Dobra' },
  { code: 'SVC', flag: '🇸🇻', country: 'sv', name: 'Salvadoran Colón' },
  { code: 'SYP', flag: '🇸🇾', country: 'sy', name: 'Syrian Pound' },
  { code: 'SZL', flag: '🇸🇿', country: 'sz', name: 'Swazi Lilangeni' },
  { code: 'THB', flag: '🇹🇭', country: 'th', name: 'Thai Baht' },
  { code: 'TJS', flag: '🇹🇯', country: 'tj', name: 'Tajikistani Somoni' },
  { code: 'TMT', flag: '🇹🇲', country: 'tm', name: 'Turkmenistani Manat' },
  { code: 'TND', flag: '🇹🇳', country: 'tn', name: 'Tunisian Dinar' },
  { code: 'TOP', flag: '🇹🇴', country: 'to', name: 'Tongan Paʻanga' },
  { code: 'TRY', flag: '🇹🇷', country: 'tr', name: 'Turkish Lira' },
  { code: 'TTD', flag: '🇹🇹', country: 'tt', name: 'Trinidad and Tobago Dollar' },
  { code: 'TWD', flag: '🇹🇼', country: 'tw', name: 'New Taiwan Dollar' },
  { code: 'TZS', flag: '🇹🇿', country: 'tz', name: 'Tanzanian Shilling' },
  { code: 'UAH', flag: '🇺🇦', country: 'ua', name: 'Ukrainian Hryvnia' },
  { code: 'UGX', flag: '🇺🇬', country: 'ug', name: 'Ugandan Shilling' },
  { code: 'USD', flag: '🇺🇸', country: 'us', name: 'US Dollar' },
  { code: 'UYU', flag: '🇺🇾', country: 'uy', name: 'Uruguayan Peso' },
  { code: 'UZS', flag: '🇺🇿', country: 'uz', name: 'Uzbekistan Som' },
  { code: 'VES', flag: '🇻🇪', country: 've', name: 'Venezuelan Bolívar' },
  { code: 'VND', flag: '🇻🇳', country: 'vn', name: 'Vietnamese Dong' },
  { code: 'VUV', flag: '🇻🇺', country: 'vu', name: 'Vanuatu Vatu' },
  { code: 'WST', flag: '🇼🇸', country: 'ws', name: 'Samoan Tala' },
  { code: 'XAF', flag: '🇨🇲', country: 'cm', name: 'CFA Franc BEAC' },
  { code: 'XCD', flag: '🇦🇬', country: 'ag', name: 'East Caribbean Dollar' },
  { code: 'XOF', flag: '🇨🇮', country: 'ci', name: 'CFA Franc BCEAO' },
  { code: 'XPF', flag: '🇵🇫', country: 'pf', name: 'CFP Franc' },
  { code: 'YER', flag: '🇾🇪', country: 'ye', name: 'Yemeni Rial' },
  { code: 'ZAR', flag: '🇿🇦', country: 'za', name: 'South African Rand' },
  { code: 'ZMW', flag: '🇿🇲', country: 'zm', name: 'Zambian Kwacha' },
  { code: 'ZWL', flag: '🇿🇼', country: 'zw', name: 'Zimbabwean Dollar' }
];

export const CURRENCY_TO_COUNTRY = CURRENCIES.reduce((acc, curr) => {
  acc[curr.code] = curr.country;
  return acc;
}, {} as Record<string, string>);
